<div class="row">
    <div class="text-center bg-danger">
        <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
                Acesso negado! Você não possui permissões para acessar a página solicitada!
        </div>
    </div>    
</div>
<div class="row">
    <div class="text-center">
        <img src="temp/Imagens/acessonegado.png" class="img-responsive" alt="Responsive image">
    </div>
</div>
