                    
                                            <br>
                                            <div class="form-group col-md-12"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Código Curso:</span>
                                                <input id="0" type="text" class="form-control" placeholder="Código Curso..." aria-describedby="sizing-addon2" name="cod_curso" value="" readonly>
                                            </div></div>   
                                            
                                            <div class="form-group col-md-12"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Curso:</span>
                                                <input  maxlength="40" id="1" type="text" class="form-control" placeholder="Curso..." aria-describedby="sizing-addon2" name="curso" value="" readonly required>
                                            </div></div>