                                         <div id="ajax"><div id="scroll" class="table-responsive">
                                              <table id="tabela" class="table <?php echo $class;?> table-bordered">
                                                <thead>                            
                                                    <tr <?php echo $theadClass;?> id="linhaCabecalho">
                                                        <th>Cod</th>
                                                        <th>Nome</th>                                                         
                                                        <th>RA</th> 
                                                        <th>Login</th> 
                                                        <th>Curso</th>
                                                        <th>Campus</th>
                                                        <th>Telefone1</th>
                                                        <th>Telefone2</th>
                                                        <th>Email</th>
                                                        <th>Perfil</th>
                                                        <th>Senha</th>
                                                    </tr>
                                                </thead>                                            
                                                <tbody>
                                                <?php if (is_array($table)){?>
                                                    <?php $dados = $table['1']; foreach ($dados as $linha){ ?>
                                                    <tr ondblclick='getValores("tabela",<?php echo $i+1;?>,"11"); myFunction("grid2", "btnNovo", "btnSalvar", "btnAtualizar", "btnEditar", "btnCancelar", "btnExcluir", this) ' onclick='getValores("tabela",<?php echo $i+1;?>,"11"); myFunction("grid", "btnNovo", "btnSalvar", "btnAtualizar", "btnEditar", "btnCancelar", "btnExcluir", this)'>
                                                        <td><?php echo $linha['cod_usuario'];?></td>
                                                        <td><?php echo $linha['nome'];?></td>
                                                        <td><?php echo $linha['ra'];?></td>
                                                        <td><?php echo $linha['login'];?></td>
                                                        <td><?php echo $linha['curso'];?></td>
                                                        <td><?php echo $linha['campus'];?></td>
                                                        <td><?php echo $linha['telefone1'];?></td>
                                                        <td><?php echo $linha['telefone2'];?></td>
                                                        <td><?php echo $linha['email'];?></td>
                                                        <td><?php echo $linha['nome_perfil'];?></td>
                                                        <td><?php echo $linha['senha'];?></td>
                                                    </tr>
                                                    <?php $i++;
                                                          } ?>
                                                          <?php }?>
                                                </tbody>
                                              </table>
                                            </div></div>        