                    
                                            <br>
                                            <div class="form-group col-md-12"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Código Status:</span>
                                                <input id="0" type="text" class="form-control" placeholder="Código Status..." aria-describedby="sizing-addon2" name="cod_status_projeto" value="" readonly>
                                            </div></div>   
                                            
                                            <div class="form-group col-md-12"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Status:</span>
                                                <input  maxlength="40" id="1" type="text" class="form-control" placeholder="Status..." aria-describedby="sizing-addon2" name="status" value="" readonly required>
                                            </div></div>