                    
                                            <br>
                                            <div class="form-group col-md-12"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Código Semestre:</span>
                                                <input id="0" type="text" class="form-control" placeholder="Código Semestre..." aria-describedby="sizing-addon2" name="cod_semestre" value="" readonly>
                                            </div></div>   
                                            
                                            <div class="form-group col-md-12"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Semestre:</span>
                                                <input  maxlength="40" id="1" type="text" class="form-control" placeholder="Semestre..." aria-describedby="sizing-addon2" name="semestre" value="" readonly required>
                                            </div></div>