                    
                                            <br>
                                            <div class="form-group col-md-12"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Código Perfil:</span>
                                                <input id="0" type="text" class="form-control" placeholder="Código Perfil..." aria-describedby="sizing-addon2" name="cod_perfil" value="" readonly>
                                            </div></div>   
                                            
                                            <div class="form-group col-md-12"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Nome do Perfil:</span>
                                                <input  maxlength="40" id="1" type="text" class="form-control" placeholder="Nome do Perfil..." aria-describedby="sizing-addon2" name="nome_perfil" value="" readonly required>
                                            </div></div>