                    
                                            <br>
                                            <div class="form-group col-md-12"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Código Campus:</span>
                                                <input id="0" type="text" class="form-control" placeholder="Código Campus..." aria-describedby="sizing-addon2" name="cod_campus" value="" readonly>
                                            </div></div>   
                                            
                                            <div class="form-group col-md-12"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Campus:</span>
                                                <input  maxlength="40" id="1" type="text" class="form-control" placeholder="Campus..." aria-describedby="sizing-addon2" name="campus" value="" readonly required>
                                            </div></div>