
    </main>
    <footer>

        <script>
            $(document).ready(function() 
            { 
                $("#tabela").tablesorter(); 
            } 
        ); 
              $('table > tbody > tr').hover(function(){
        $(this).toggleClass('hover');
      });
      $(document).ready(function() {
    $('.js-example-basic-multiple').select2();
});
        </script>
        <!-- MASCARAS -->
        <script type="text/javascript">
        $('.cpf').mask('000.000.000-00', {reverse: true});
        $('.cnpj').mask('00.000.000/0000-00', {reverse: true}); 
        $('.cep').mask('00000-000');
        $('.money').mask("#.##0,00", {reverse: true});
        
        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
            },
            spOptions = {
            onKeyPress: function(val, e, field, options) {
                field.mask(SPMaskBehavior.apply({}, arguments), options);
                }
            };

            $('.tel').mask(SPMaskBehavior, spOptions);
        </script>
    </footer>
  </body>
</html>