<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" lang="pt-br">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Una Projetos</title>

        <!-- Bootstrap -->
        <link href="css/bootstrap.css" rel="stylesheet">
        <link href="css/theme.css" rel="stylesheet">
        <link rel="icon" href="">
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesnt work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <!-- jQuery (necessary for Bootstraps JavaScript plugins) -->
        <!--script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-latest.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="js/bootstrap.min.js"></script>
        <script type="text/javascript" src="js/funcoes.js"></script>
        <script type="text/javascript" src="js/get.js"></script>
        <script type="text/javascript" src="js/ajax.js"></script>         
        <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>-->
        <!--script src="http://tablesorter.com/__jquery.tablesorter.min.js" type="text/javascript"></script-->
        <script src="js/jquery.tablesorter.min.js"></script>
        <script type="text/javascript" src="js/jquery.mask.min.js"></script>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
        <script>
            $(document).ready(function() {
            $('#myModal').modal('show');
        });
        </script>
        <script type="text/javascript" src="js/cep.js"></script>
    </head>
    <body onload='myFunction("<?php echo $btn;?>", "btnNovo", "btnSalvar", "btnAtualizar", "btnEditar", "btnCancelar", "btnExcluir", this)'>
        <header>
        <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarCollapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href=<?php echo "'" . "http://$_SERVER[HTTP_HOST]" ."'"; ?>>Una Projetos</a>
            </div>          
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href=<?php echo "'" . "http://$_SERVER[HTTP_HOST]" ."'"; ?>>Home<span class="sr-only">(current)</span></a></li>
                    
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cadastros<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?php echo "http://$_SERVER[HTTP_HOST]" ."/cadastrocampus"; ?>">Campus</a></li>
                        <li><a href="<?php echo "http://$_SERVER[HTTP_HOST]" ."/cadastrocurso"; ?>">Cursos</a></li>
                        <li><a href="<?php echo "http://$_SERVER[HTTP_HOST]" ."/cadastrosemestre"; ?>">Semestres</a></li>
                        <li><a href="<?php echo "http://$_SERVER[HTTP_HOST]" ."/cadastrostatusprojeto"; ?>">Status de Projeto</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="<?php echo "http://$_SERVER[HTTP_HOST]" ."/cadastrousuario"; ?>">Usuários</a></li>
                        <li><a href="<?php echo "http://$_SERVER[HTTP_HOST]" ."/cadastroperfilusuario"; ?>">Perfis de Usuário</a></li>
                        <li><a href="<?php echo "http://$_SERVER[HTTP_HOST]" ."/cadastropermissoes"; ?>">Permissões de Usuário</a></li>
                    </ul>
                    </li>
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Projetos<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?php echo "http://$_SERVER[HTTP_HOST]" ."/postagemprojeto"; ?>">Postar Projeto</a></li>
                        <li><a href="<?php echo "http://$_SERVER[HTTP_HOST]" ."/consultaprojeto"; ?>">Consultar Projetos</a></li>
                        <li><a href="<?php echo "http://$_SERVER[HTTP_HOST]" ."/analiseprojeto"; ?>">Aprovar Projetos</a></li>
                    </ul>
                    </li>
                    
                </ul>      
                <ul class="nav navbar-nav navbar-right">        <?php if(isset($_SESSION['codusuario'])){ $ra = $_SESSION['codusuario']; $usuario = $_SESSION['usuario'];}else{ $usuario="";$ra=""; } ?>
                    <li><a href="<?php echo "http://$_SERVER[HTTP_HOST]/$usuario?cod-usuario=$ra&submit=consultar"; ?>">Meu Perfil</a></li>
                    <li><a href="<?php echo "http://$_SERVER[HTTP_HOST]" ."/logout"; ?>">Sair do Sistema</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container- -->
        </nav>
    </header>
    <main>