                    
                                            <br>
                                            <div class="form-group col-md-6"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Código Instituição:</span>
                                                <input id="0" type="text" class="form-control" placeholder="Código Instituição..." aria-describedby="sizing-addon2" name="codInstituicao" value="" readonly>
                                            </div></div>
                                            
                                            <div class="form-group col-md-6"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">CNPJ:</span>
                                                <input maxlength="18" id="1" type="text" class="form-control cnpj" placeholder="00.000.000/0000-00" aria-describedby="sizing-addon2" name="cnpj" value="" readonly required>
                                            </div></div>
                                            <br>
                                            <div class="form-group col-md-12"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Razão Social:</span>
                                                <input maxlength="100" id="2" type="text" class="form-control" placeholder="Razão Social..." aria-describedby="sizing-addon2" name="razaoSocial" value="" readonly required>
                                            </div></div>
                                            <br>
                                            <div class="form-group col-md-12"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Nome Fantasia:</span>
                                                <input maxlength="100"  id="3" type="text" class="form-control" placeholder="Nome Fantasia..." aria-describedby="sizing-addon2" name="nomeFantasia" value="" readonly>
                                            </div></div>
                                            <br>
                                            <div class="form-group col-md-6"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Inscrição Estadual:</span>
                                                <input id="4" type="text" class="form-control" placeholder="Inscrição Estadual..." aria-describedby="sizing-addon2" name="inscEstadual" value="" readonly>
                                            </div></div>
                                            <br>
                                            <div class="form-group col-md-6"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Inscrição Municipal:</span>
                                                <input id="5" type="text" class="form-control" placeholder="Inscrição Municipal..." aria-describedby="sizing-addon2" name="inscMunicipal" value="" readonly>
                                            </div></div>
                                            <br>
                                            <div class="form-group col-md-3"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">CEP:</span>
                                                <input maxlength="9" onblur="pesquisacep(this.value,'7','10','11','12')" id="6" type="text" class="form-control cep" placeholder="00.000-00" aria-describedby="sizing-addon2" name="cep" value="" readonly>
                                            </div></div>
                                            <br>
                                            <div class="form-group col-md-3"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Número:</span>
                                                <input id="8" type="text" class="form-control" placeholder="Número..." aria-describedby="sizing-addon2" name="numero" value="" readonly>
                                            </div></div>                                            
                                            <br>
                                            <div class="form-group col-md-6"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Logradouro:</span>
                                                <input id="7" type="text" class="form-control" placeholder="Logradouro..." aria-describedby="sizing-addon2" name="logradouro" value="" readonly>
                                            </div></div>
                                            <br>
                                            <div class="form-group col-md-6"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Complemento:</span>
                                                <input id="9" type="text" class="form-control" placeholder="Complemento..." aria-describedby="sizing-addon2" name="complemento" value="" readonly>
                                            </div></div>
                                            <br>
                                            <div class="form-group col-md-6"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Bairro:</span>
                                                <input id="10" type="text" class="form-control" placeholder="Bairro..." aria-describedby="sizing-addon2" name="bairro" value="" readonly>
                                            </div></div>
                                            <br>
                                            <div class="form-group col-md-6"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Cidade:</span>
                                                <input id="11" type="text" class="form-control" placeholder="Cidade..." aria-describedby="sizing-addon2" name="cidade" value="" readonly>
                                            </div></div>
                                            <br>
                                            <div class="form-group col-md-6"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Estado:</span>
                                                <select id="12" class="form-control" placeholder="Estado..." aria-describedby="sizing-addon2" name="estado" required>
                                                    <option value="">Selecione uma opção...</option>
                                                    <option value="AC">AC</option>
                                                    <option value="AL">AL</option>
                                                    <option value="AM">AM</option>
                                                    <option value="AP">AP</option>
                                                    <option value="BA">BA</option>
                                                    <option value="CE">CE</option>
                                                    <option value="DF">DF</option>
                                                    <option value="ES">ES</option>
                                                    <option value="GO">GO</option>
                                                    <option value="MA">MA</option>
                                                    <option value="MT">MT</option>
                                                    <option value="MS">MS</option>
                                                    <option value="MG">MG</option>
                                                    <option value="PA">PA</option>
                                                    <option value="PB">PB</option>
                                                    <option value="PR">PR</option>
                                                    <option value="PE">PE</option>
                                                    <option value="PI">PI</option>
                                                    <option value="RJ">RJ</option>
                                                    <option value="RN">RN</option>
                                                    <option value="RO">RO</option>
                                                    <option value="RS">RS</option>
                                                    <option value="RR">RR</option>
                                                    <option value="SC">SC</option>
                                                    <option value="SE">SE</option>
                                                    <option value="SP">SP</option>
                                                    <option value="TO">TO</option>
                                                </select>
                                            </div></div>
                                            <br>
                                            <div class="form-group col-md-3"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Telefone:</span>
                                                <input maxlength="15" id="13" type="text" class="form-control tel" placeholder="(00) 0000-0000..." aria-describedby="sizing-addon2" name="tel1" value="" readonly>
                                            </div></div>
                                            <br>
                                            <div class="form-group col-md-3"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Telefone:</span>
                                                <input maxlength="15" id="14" type="tel" class="form-control tel" placeholder="(00) 0000-0000..." aria-describedby="sizing-addon2" name="tel2" value="" readonly>
                                            </div></div>
                                            <br>
                                            <div class="form-group col-md-3"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Telefone:</span>
                                                <input maxlength="15" id="15" type="tel" class="form-control tel" placeholder="(00) 0000-0000..." aria-describedby="sizing-addon2" name="tel3" value="" readonly>
                                            </div></div>
                                            <br>
                                            <div class="form-group col-md-3"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Telefone:</span>
                                                <input maxlength="15" id="16" type="tel" class="form-control tel" placeholder="(00) 0000-0000..." aria-describedby="sizing-addon2" name="tel4" value="" readonly>
                                            </div></div>
                                            <br>
                                            <div class="form-group col-md-3"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Email:</span>
                                                <input id="17" type="email" class="form-control" placeholder="Email Instituição..." aria-describedby="sizing-addon2" name="emailInstituicao" readonly>
                                            </div></div>
                                            <br>
                                            <div class="form-group col-md-3"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Site:</span>
                                                <input id="18" type="text" class="form-control" placeholder="www.seusite.com.br" aria-describedby="sizing-addon2" name="site" value="" readonly>
                                            </div></div>
                                            <br>
                                            <div class="form-group col-md-6"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Logomarca:</span>
                                                <input type="file" class="form-control" aria-describedby="sizing-addon2" name="logomarca">
                                            </div></div>
                                            <br>