                                            <?php //var_dump($table['3']);?>
                                            <br>
                                            <div class="form-group col-md-12"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Código Integrante:</span>
                                                <input id="0" type="text" class="form-control" placeholder="Código Integrante..." aria-describedby="sizing-addon2" name="cod_integrante" value="" readonly>
                                            </div></div>   
                                            
                                            <div class="form-group col-md-12"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Projeto:</span>
                                                <select id="2" class="form-control" placeholder="Projeto..." aria-describedby="sizing-addon2" name="cod_projeto" value="" required>
                                                    <option value="">Selecione uma opção...</option>
                                                    <?php if (is_array($table)){?>
                                                    <?php $i=0; $dados = $table['1']; foreach ($dados as $linha){;?>
                                                    <option value="<?php echo $linha['cod_projeto'];?>"><?php echo $linha['nome_projeto'];?></option>
                                                        <?php } ?>
                                                    <?php $i++;
                                                    } ?>
                                                </select>
                                            </div></div>
                                            
                                            <div class="form-group col-md-12"><div class="input-group">
                                                <span class="input-group-addon" id="sizing-addon2">Integrante:</span>
                                                <select id="1" class="form-control" placeholder="Integrante..." aria-describedby="sizing-addon2" name="cod_usuario" value="" required>
                                                    <option value="">Selecione uma opção...</option>
                                                    <?php if (is_array($table)){?>
                                                    <?php $i=0; $dados = $table['2']; foreach ($dados as $linha){;?>
                                                    <option value="<?php echo $linha['cod_usuario'];?>"><?php echo $linha['nome'];?></option>
                                                        <?php } ?>
                                                    <?php $i++;
                                                    } ?>
                                                </select>
                                            </div></div>