                                         <div id="ajax"><div id="scroll" class="table-responsive">
                                              <table id="tabela" class="table <?php echo $class;?> table-bordered">
                                                <thead>                            
                                                    <tr <?php echo $theadClass;?> id="linhaCabecalho">
                                                        <th>Cod</th>
                                                        <th>Perfil</th>
                                                        <th>Adicionar Projeto</th>
                                                        <th>Editar Projeto</th>
                                                        <th>Excluir Projeto</th>
                                                        <th>Gerenciar Usuário</th>
                                                        <th>Aprovar Trabalho</th>
                                                    </tr>
                                                </thead>                                            
                                                <tbody>
                                                <?php if (is_array($table)){?>
                                                    <?php $dados = $table['1']; foreach ($dados as $linha){ ?>
                                                    <tr ondblclick='getValores("tabela",<?php echo $i+1;?>,"7"); myFunction("grid2", "btnNovo", "btnSalvar", "btnAtualizar", "btnEditar", "btnCancelar", "btnExcluir", this) ' onclick='getValores("tabela",<?php echo $i+1;?>,"7"); myFunction("grid", "btnNovo", "btnSalvar", "btnAtualizar", "btnEditar", "btnCancelar", "btnExcluir", this)'>
                                                        <td><?php echo $linha['cod_permissao'];?></td>
                                                        <td><?php echo $linha['nome_perfil'];?></td>
                                                        <td><?php echo $linha['adcionar_projeto'];?></td>
                                                        <td><?php echo $linha['editar_projeto'];?></td>
                                                        <td><?php echo $linha['excluir_projeto'];?></td>
                                                        <td><?php echo $linha['gerenciar_usuario'];?></td>
                                                        <td><?php echo $linha['aprovar_trabalho'];?></td>
                                                    </tr>
                                                    <?php $i++;
                                                          } ?>
                                                          <?php }?>
                                                </tbody>
                                              </table>
                                            </div></div>        